# Define the target document name (without extension)
TARGET = main

# Define auxiliary files generated by LaTeX that you want to clean
AUXFILES = $(TARGET).aux $(TARGET).log $(TARGET).out $(TARGET).toc $(TARGET).lof $(TARGET).lot $(TARGET).bbl $(TARGET).blg $(TARGET).fls $(TARGET).fdb_latexmk $(TARGET).synctex.gz

# Define the TeX engine to use (pdflatex, xelatex, lualatex)
LATEX = pdflatex

# Rule for compiling the .tex file
all: $(TARGET).pdf

# Compile the .tex file
	$(LATEX) $(TARGET).tex
	bibtex $(TARGET).aux
	$(LATEX) $(TARGET).tex
	$(LATEX) $(TARGET).tex

	rm -f $(AUXFILES)

# Rule for deep clean (including PDF file)
deepclean: clean
	rm -f $(TARGET).pdf

.PHONY: all deepclean

